### PR TITLE
feat: add metadata in a comment to the body of the issue. 

### LINKED ISSUE #558: Add suggested semver metadata in a hidden comment to the body of the generated issue for easier and more robust parsing by automated tools
For inspiration, see the code for generating pull requests by the optic release automation action, which adds the following to the body of the PR:

```
<!--
<release-meta>{"id":107569122,"version":"v4.7.0","npmTag":"latest","opticUrl":"https://optic-zf3votdk5a-ew.a.run.app/api/generate/"}</release-meta>
-->
```

https://github.com/nearform-actions/optic-release-automation-action/blob/afd3560cf10a430f19830a1c8d3b7756c8124400/src/pr.tpl#L33

https://github.com/nearform-actions/optic-release-automation-action/blob/afd3560cf10a430f19830a1c8d3b7756c8124400/src/openPr.js#L124

### PR DESCRIPTION
**Pull request by ergusto**
Resolves #558

### CODE REVIEW

**Review by simoneb — CHANGES_REQUESTED** [review]
write a test please

**Comment by ergusto** [comment]
@simoneb Is this feature still required? I'd be happy to finish this and add some tests if it would still be useful.

**Comment by simoneb** [comment]
@ergusto sorry for missing this one. I think this was probably to be used in our release automation tool right? If so, we could both do this one, and the change in there to reflect this. How does it sound?

**Comment by ergusto** [comment]
Should this project's CI include requiring succesful tests before merging a PR?

**Comment by simoneb** [comment]
@ergusto required approval to run because of the external contribution. It's failed now

**Comment by ergusto** [comment]
@simoneb Fixed the linting.

**Review by simoneb — APPROVED** [review]
LGTM 👌

**Comment by ergusto** [comment]
@simoneb Tests were producing a different result on CI than locally, have updated to mock `conventional-changelog-monorepo/conventional-recommended-bump` package.

**Review by simoneb — APPROVED** [review]

**Comment by ergusto** [comment]
@simoneb I don't have the required permissions to merge this unfortunately, could you merge it please?

**Pull request merged**
